
import java.sql.*;
//import mysql.jdbc.Connection;
//import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ketan Pandey
 */
public class SMS extends javax.swing.JFrame {

    /**
     * Creates new form SMS
     */
    public SMS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Add_teacher = new javax.swing.JFrame();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        tqual = new javax.swing.JTextField();
        tsub = new javax.swing.JTextField();
        tclass = new javax.swing.JTextField();
        tgen = new javax.swing.JComboBox();
        tpass = new javax.swing.JPasswordField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        teachersub = new javax.swing.JButton();
        teachersub1 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tdob = new javax.swing.JFormattedTextField();
        tdoj = new javax.swing.JFormattedTextField();
        jLabel39 = new javax.swing.JLabel();
        Add_student = new javax.swing.JFrame();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        StAdno = new javax.swing.JTextField();
        StClass = new javax.swing.JTextField();
        StSec = new javax.swing.JTextField();
        StGen = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        StSub1 = new javax.swing.JButton();
        StSub = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        StDob = new javax.swing.JFormattedTextField();
        StDoj = new javax.swing.JFormattedTextField();
        StName = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        Student_Details = new javax.swing.JFrame();
        jScrollPane12 = new javax.swing.JScrollPane();
        student_detail = new javax.swing.JTable();
        adminFrame = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        remove_teacher = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        id_remove = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        remove_student = new javax.swing.JFrame();
        jLabel13 = new javax.swing.JLabel();
        id_remove2 = new javax.swing.JTextField();
        removeStudentlabel = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        Extra = new javax.swing.JFrame();
        jScrollPane9 = new javax.swing.JScrollPane();
        teacherTbl = new javax.swing.JTable();
        jScrollPane11 = new javax.swing.JScrollPane();
        adminTbl = new javax.swing.JTable();
        jButton19 = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        studenttbl = new javax.swing.JTable();
        Marksheet = new javax.swing.JFrame();
        jScrollPane7 = new javax.swing.JScrollPane();
        mark = new javax.swing.JTable();
        Teacher_frame = new javax.swing.JFrame();
        jButton13 = new javax.swing.JButton();
        name3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        credits = new javax.swing.JFrame();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        Add_marks = new javax.swing.JFrame();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        a2 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        a9 = new javax.swing.JTextField();
        a7 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        teachersub2 = new javax.swing.JButton();
        teachersub3 = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        a1 = new javax.swing.JTextField();
        a4 = new javax.swing.JTextField();
        a6 = new javax.swing.JTextField();
        a5 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        a8 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        adminRbtn = new javax.swing.JRadioButton();
        teacherRbtn = new javax.swing.JRadioButton();
        usernameCbox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        pwdFld = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        Add_teacher.setTitle("Add Teacher");
        Add_teacher.setLocation(new java.awt.Point(710, 240));
        Add_teacher.setMinimumSize(new java.awt.Dimension(448, 450));
        Add_teacher.setUndecorated(true);
        Add_teacher.setResizable(false);
        Add_teacher.getContentPane().setLayout(null);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 255));
        jLabel24.setText("Username:");
        Add_teacher.getContentPane().add(jLabel24);
        jLabel24.setBounds(40, 60, 140, 20);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 255));
        jLabel27.setText("Qualification:");
        Add_teacher.getContentPane().add(jLabel27);
        jLabel27.setBounds(40, 170, 160, 30);

        jLabel32.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 204, 255));
        jLabel32.setText("Password:");
        Add_teacher.getContentPane().add(jLabel32);
        jLabel32.setBounds(40, 100, 130, 20);

        jLabel33.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 204, 255));
        jLabel33.setText("Class Teacher:");
        Add_teacher.getContentPane().add(jLabel33);
        jLabel33.setBounds(40, 210, 160, 30);

        jLabel34.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(204, 204, 255));
        jLabel34.setText("Gender:");
        Add_teacher.getContentPane().add(jLabel34);
        jLabel34.setBounds(40, 134, 110, 20);

        jLabel35.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 204, 255));
        jLabel35.setText("Subject:");
        Add_teacher.getContentPane().add(jLabel35);
        jLabel35.setBounds(40, 250, 110, 30);

        tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnameActionPerformed(evt);
            }
        });
        Add_teacher.getContentPane().add(tname);
        tname.setBounds(200, 50, 200, 30);
        Add_teacher.getContentPane().add(tqual);
        tqual.setBounds(200, 170, 200, 30);

        tsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsubActionPerformed(evt);
            }
        });
        Add_teacher.getContentPane().add(tsub);
        tsub.setBounds(200, 250, 200, 30);
        Add_teacher.getContentPane().add(tclass);
        tclass.setBounds(200, 210, 200, 30);

        tgen.setMaximumRowCount(3);
        tgen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        Add_teacher.getContentPane().add(tgen);
        tgen.setBounds(200, 130, 140, 30);

        tpass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Add_teacher.getContentPane().add(tpass);
        tpass.setBounds(200, 90, 200, 30);

        jLabel36.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(204, 204, 255));
        jLabel36.setText("DOJ:");
        Add_teacher.getContentPane().add(jLabel36);
        jLabel36.setBounds(40, 290, 90, 30);

        jLabel37.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 204, 255));
        jLabel37.setText("DOB:");
        Add_teacher.getContentPane().add(jLabel37);
        jLabel37.setBounds(40, 330, 90, 30);

        teachersub.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        teachersub.setText("Submit");
        teachersub.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        teachersub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachersubActionPerformed(evt);
            }
        });
        Add_teacher.getContentPane().add(teachersub);
        teachersub.setBounds(100, 380, 120, 40);

        teachersub1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        teachersub1.setText("Cancel");
        teachersub1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        teachersub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachersub1ActionPerformed(evt);
            }
        });
        Add_teacher.getContentPane().add(teachersub1);
        teachersub1.setBounds(250, 380, 120, 40);

        jLabel38.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(204, 204, 255));
        jLabel38.setText("<html><b>Add Teacher</b></html> ");
        Add_teacher.getContentPane().add(jLabel38);
        jLabel38.setBounds(140, 0, 160, 30);
        Add_teacher.getContentPane().add(jSeparator1);
        jSeparator1.setBounds(-10, 40, 720, 10);

        tdob.setText("YYYY/MM/DD");
        tdob.setToolTipText("dd/mm/yyyy");
        Add_teacher.getContentPane().add(tdob);
        tdob.setBounds(200, 330, 200, 30);

        tdoj.setText("YYYY/MM/DD");
        tdoj.setToolTipText("dd/mm/yyyy");
        Add_teacher.getContentPane().add(tdoj);
        tdoj.setBounds(200, 290, 200, 30);

        jLabel39.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 204, 255));
        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XII Project/back - Copy.jpg"))); // NOI18N
        Add_teacher.getContentPane().add(jLabel39);
        jLabel39.setBounds(0, 0, 1600, 1200);

        Add_student.setTitle("Add Student");
        Add_student.setLocation(new java.awt.Point(710, 240));
        Add_student.setMinimumSize(new java.awt.Dimension(448, 450));
        Add_student.setUndecorated(true);
        Add_student.setResizable(false);
        Add_student.getContentPane().setLayout(null);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 255));
        jLabel25.setText("Name:");
        Add_student.getContentPane().add(jLabel25);
        jLabel25.setBounds(30, 60, 100, 14);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 255));
        jLabel26.setText("Class:");
        Add_student.getContentPane().add(jLabel26);
        jLabel26.setBounds(30, 170, 120, 30);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 204, 255));
        jLabel28.setText("Admission no.:");
        Add_student.getContentPane().add(jLabel28);
        jLabel28.setBounds(30, 100, 120, 14);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 204, 255));
        jLabel29.setText("Section:");
        Add_student.getContentPane().add(jLabel29);
        jLabel29.setBounds(30, 210, 120, 30);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 204, 255));
        jLabel30.setText("Gender:");
        Add_student.getContentPane().add(jLabel30);
        jLabel30.setBounds(30, 140, 70, 14);
        Add_student.getContentPane().add(StAdno);
        StAdno.setBounds(200, 90, 180, 30);
        Add_student.getContentPane().add(StClass);
        StClass.setBounds(200, 170, 180, 30);
        Add_student.getContentPane().add(StSec);
        StSec.setBounds(200, 210, 180, 30);

        StGen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StGen.setMaximumRowCount(3);
        StGen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        Add_student.getContentPane().add(StGen);
        StGen.setBounds(200, 130, 120, 30);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 204, 255));
        jLabel31.setText("DOJ:");
        Add_student.getContentPane().add(jLabel31);
        jLabel31.setBounds(30, 250, 50, 30);

        jLabel40.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(204, 204, 255));
        jLabel40.setText("DOB:");
        Add_student.getContentPane().add(jLabel40);
        jLabel40.setBounds(30, 300, 50, 20);

        StSub1.setBackground(new java.awt.Color(204, 204, 204));
        StSub1.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        StSub1.setText("Cancel");
        StSub1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        StSub1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StSub1ActionPerformed(evt);
            }
        });
        Add_student.getContentPane().add(StSub1);
        StSub1.setBounds(260, 350, 140, 40);

        StSub.setBackground(new java.awt.Color(204, 204, 204));
        StSub.setFont(new java.awt.Font("SimSun", 1, 24)); // NOI18N
        StSub.setText("Submit");
        StSub.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        StSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StSubActionPerformed(evt);
            }
        });
        Add_student.getContentPane().add(StSub);
        StSub.setBounds(80, 350, 140, 40);

        jLabel41.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 204, 255));
        jLabel41.setText("<html><b>Add Student</b></html> ");
        Add_student.getContentPane().add(jLabel41);
        jLabel41.setBounds(150, 0, 160, 30);
        Add_student.getContentPane().add(jSeparator2);
        jSeparator2.setBounds(-10, 40, 720, 10);

        StDob.setText("YYYY/MM/DD");
        StDob.setToolTipText("");
        StDob.setVerifyInputWhenFocusTarget(false);
        Add_student.getContentPane().add(StDob);
        StDob.setBounds(200, 290, 180, 30);

        StDoj.setText("YYYY/MM/DD");
        StDoj.setToolTipText("dd/mm/yyyy");
        Add_student.getContentPane().add(StDoj);
        StDoj.setBounds(200, 250, 180, 30);
        Add_student.getContentPane().add(StName);
        StName.setBounds(200, 50, 180, 30);

        jLabel42.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(204, 204, 255));
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XII Project/back - Copy.jpg"))); // NOI18N
        Add_student.getContentPane().add(jLabel42);
        jLabel42.setBounds(0, 0, 1600, 1200);

        Student_Details.setTitle("Students Details");
        Student_Details.setLocation(new java.awt.Point(250, 100));
        Student_Details.setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        Student_Details.setMinimumSize(new java.awt.Dimension(910, 590));
        Student_Details.setResizable(false);

        student_detail.setAutoCreateRowSorter(true);
        student_detail.setBackground(new java.awt.Color(204, 204, 204));
        student_detail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Admission_No", "Gender", "Class", "Section", "DOJ", "DOB"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        student_detail.setEnabled(false);
        student_detail.getTableHeader().setReorderingAllowed(false);
        jScrollPane12.setViewportView(student_detail);

        javax.swing.GroupLayout Student_DetailsLayout = new javax.swing.GroupLayout(Student_Details.getContentPane());
        Student_Details.getContentPane().setLayout(Student_DetailsLayout);
        Student_DetailsLayout.setHorizontalGroup(
            Student_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
        );
        Student_DetailsLayout.setVerticalGroup(
            Student_DetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );

        adminFrame.setTitle("Admin");
        adminFrame.setLocation(new java.awt.Point(710, 240));
        adminFrame.setMinimumSize(new java.awt.Dimension(448, 450));
        adminFrame.setUndecorated(true);
        adminFrame.setResizable(false);
        adminFrame.getContentPane().setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Login As:");
        adminFrame.getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 0, 100, 50);

        jButton3.setFont(new java.awt.Font("Sanskrit Text", 1, 24)); // NOI18N
        jButton3.setText("Remove Teacher");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        adminFrame.getContentPane().add(jButton3);
        jButton3.setBounds(210, 140, 230, 60);

        jButton2.setFont(new java.awt.Font("Sanskrit Text", 1, 24)); // NOI18N
        jButton2.setText("Remove Student");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        adminFrame.getContentPane().add(jButton2);
        jButton2.setBounds(210, 240, 230, 60);

        jButton15.setFont(new java.awt.Font("Sanskrit Text", 1, 24)); // NOI18N
        jButton15.setText("Add Teacher");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        adminFrame.getContentPane().add(jButton15);
        jButton15.setBounds(10, 140, 190, 60);

        jButton21.setFont(new java.awt.Font("Sanskrit Text", 1, 24)); // NOI18N
        jButton21.setText("Add Student");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        adminFrame.getContentPane().add(jButton21);
        jButton21.setBounds(10, 240, 190, 60);

        jButton22.setFont(new java.awt.Font("Sanskrit Text", 1, 24)); // NOI18N
        jButton22.setText("View Database");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        adminFrame.getContentPane().add(jButton22);
        jButton22.setBounds(10, 350, 430, 60);

        name.setBackground(new java.awt.Color(83, 127, 243));
        name.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name.setText("Admin");
        name.setEnabled(false);
        adminFrame.getContentPane().add(name);
        name.setBounds(10, 50, 180, 40);

        jButton7.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        jButton7.setText("Log out");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        adminFrame.getContentPane().add(jButton7);
        jButton7.setBounds(300, 20, 130, 40);

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XII Project/back - Copy.jpg"))); // NOI18N
        adminFrame.getContentPane().add(jLabel48);
        jLabel48.setBounds(-740, -170, 1400, 710);

        remove_teacher.setTitle("Remove Student");
        remove_teacher.setLocation(new java.awt.Point(725, 300));
        remove_teacher.setMinimumSize(new java.awt.Dimension(330, 202));
        remove_teacher.setUndecorated(true);
        remove_teacher.setResizable(false);
        remove_teacher.getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("Enter ID:");
        remove_teacher.getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 70, 70, 30);
        remove_teacher.getContentPane().add(id_remove);
        id_remove.setBounds(100, 70, 140, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 255));
        jLabel8.setText("Remove Teacher");
        remove_teacher.getContentPane().add(jLabel8);
        jLabel8.setBounds(25, 11, 267, 44);

        jButton5.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        jButton5.setText("Remove");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        remove_teacher.getContentPane().add(jButton5);
        jButton5.setBounds(20, 140, 130, 40);

        jButton8.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        jButton8.setText("Cancel");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        remove_teacher.getContentPane().add(jButton8);
        jButton8.setBounds(180, 140, 120, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XII Project/back - Copy.jpg"))); // NOI18N
        remove_teacher.getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 480, 280);

        remove_student.setLocation(new java.awt.Point(725, 300));
        remove_student.setMinimumSize(new java.awt.Dimension(330, 202));
        remove_student.setUndecorated(true);
        remove_student.setResizable(false);
        remove_student.getContentPane().setLayout(null);

        jLabel13.setFont(new java.awt.Font("Sitka Banner", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 255));
        jLabel13.setText("Enter Adm. No.:");
        remove_student.getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 70, 130, 30);
        remove_student.getContentPane().add(id_remove2);
        id_remove2.setBounds(150, 70, 140, 30);

        removeStudentlabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        removeStudentlabel.setForeground(new java.awt.Color(153, 153, 255));
        removeStudentlabel.setText("Remove Student");
        remove_student.getContentPane().add(removeStudentlabel);
        removeStudentlabel.setBounds(25, 11, 262, 44);

        jButton9.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        jButton9.setText("Remove");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        remove_student.getContentPane().add(jButton9);
        jButton9.setBounds(20, 140, 130, 40);

        jButton10.setFont(new java.awt.Font("Swis721 BT", 1, 24)); // NOI18N
        jButton10.setText("Cancel");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        remove_student.getContentPane().add(jButton10);
        jButton10.setBounds(180, 140, 120, 40);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XII Project/back - Copy.jpg"))); // NOI18N
        remove_student.getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 480, 280);

        Extra.setTitle("Database");

        teacherTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Password", "Gender", "Qualification", "Class Teacher", "Subject", "DOJ", "DOB"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(teacherTbl);

        adminTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane11.setViewportView(adminTbl);

        jButton19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton19.setText("<HTML> R <BR> E <BR>T <BR>R <BR>I <BR>E <BR>V <BR>E <BR> <BR>D <BR>A <BR>T <BR>A");
        jButton19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        studenttbl.setAutoCreateRowSorter(true);
        studenttbl.setBackground(new java.awt.Color(204, 204, 204));
        studenttbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Admission_No", "Gender", "Class", "Section", "DOJ", "DOB"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studenttbl.setEnabled(false);
        studenttbl.getTableHeader().setReorderingAllowed(false);
        jScrollPane13.setViewportView(studenttbl);

        javax.swing.GroupLayout ExtraLayout = new javax.swing.GroupLayout(Extra.getContentPane());
        Extra.getContentPane().setLayout(ExtraLayout);
        ExtraLayout.setHorizontalGroup(
            ExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExtraLayout.createSequentialGroup()
                .addGroup(ExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExtraLayout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 949, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        ExtraLayout.setVerticalGroup(
            ExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExtraLayout.createSequentialGroup()
                .addGroup(ExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ExtraLayout.createSequentialGroup()
                        .addGroup(ExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(ExtraLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Marksheet.setTitle("Marksheet");
        Marksheet.setMinimumSize(new java.awt.Dimension(1024, 800));

        mark.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Admission_no", "Name", "Class", "English", "Physics", "Chemistry", "Maths", "PEd", "IP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(mark);

        javax.swing.GroupLayout MarksheetLayout = new javax.swing.GroupLayout(Marksheet.getContentPane());
        Marksheet.getContentPane().setLayout(MarksheetLayout);
        MarksheetLayout.setHorizontalGroup(
            MarksheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1140, Short.MAX_VALUE)
        );
        MarksheetLayout.setVerticalGroup(
            MarksheetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
        );

        Teacher_frame.setTitle("Teacher");
        Teacher_frame.setLocation(new java.awt.Point(710, 240));
        Teacher_frame.setMinimumSize(new java.awt.Dimension(448, 450));
        Teacher_frame.setUndecorated(true);
        Teacher_frame.setResizable(false);
        Teacher_frame.getContentPane().setLayout(null);

        jButton13.setFont(new java.awt.Font("Sitka Subheading", 1, 24)); // NOI18N
        jButton13.setText("Log out");
        jButton13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        Teacher_frame.getContentPane().add(jButton13);
        jButton13.setBounds(290, 10, 130, 40);

        name3.setBackground(new java.awt.Color(83, 127, 243));
        name3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        name3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        name3.setText("Teacher");
        name3.setEnabled(false);
        Teacher_frame.getContentPane().add(name3);
        name3.setBounds(10, 50, 180, 40);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel17.setText("Login As:");
        Teacher_frame.getContentPane().add(jLabel17);
        jLabel17.setBounds(10, 0, 100, 50);

        jButton25.setFont(new java.awt.Font("Sanskrit Text", 1, 24)); // NOI18N
        jButton25.setText("View Student's Details");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        Teacher_frame.getContentPane().add(jButton25);
        jButton25.setBounds(30, 230, 350, 60);

        jButton26.setFont(new java.awt.Font("Sanskrit Text", 1, 24)); // NOI18N
        jButton26.setText("Add Student's Marks");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        Teacher_frame.getContentPane().add(jButton26);
        jButton26.setBounds(30, 320, 350, 60);

        jButton27.setFont(new java.awt.Font("Sanskrit Text", 1, 24)); // NOI18N
        jButton27.setText("View Student's Marksheet");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        Teacher_frame.getContentPane().add(jButton27);
        jButton27.setBounds(30, 150, 350, 60);

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XII Project/back - Copy.jpg"))); // NOI18N
        Teacher_frame.getContentPane().add(jLabel47);
        jLabel47.setBounds(-890, -130, 1350, 580);

        credits.setTitle("Credits");
        credits.setLocation(new java.awt.Point(250, 100));
        credits.setMinimumSize(new java.awt.Dimension(910, 590));
        credits.setUndecorated(true);
        credits.setResizable(false);
        credits.getContentPane().setLayout(null);

        jButton6.setBackground(new java.awt.Color(153, 0, 51));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        credits.getContentPane().add(jButton6);
        jButton6.setBounds(820, 10, 80, 31);

        jLabel9.setFont(new java.awt.Font("Segoe Marker", 1, 48)); // NOI18N
        jLabel9.setText("<html><u>Credits</u>:</html>");
        credits.getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 10, 190, 57);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XII Project/ketan.png"))); // NOI18N
        credits.getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 100, 250, 250);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XII Project/shiva.png"))); // NOI18N
        credits.getContentPane().add(jLabel14);
        jLabel14.setBounds(560, 90, 290, 270);

        jLabel16.setFont(new java.awt.Font("Script MT Bold", 1, 48)); // NOI18N
        jLabel16.setText("Ketan Pandey");
        credits.getContentPane().add(jLabel16);
        jLabel16.setBounds(60, 350, 350, 130);

        jLabel18.setFont(new java.awt.Font("Script MT Bold", 1, 48)); // NOI18N
        jLabel18.setText("Shiva Budhlakoti");
        credits.getContentPane().add(jLabel18);
        jLabel18.setBounds(500, 370, 400, 90);

        jSeparator4.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator4.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        credits.getContentPane().add(jSeparator4);
        jSeparator4.setBounds(450, 80, 20, 400);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XII Project/back - Copy.jpg"))); // NOI18N
        credits.getContentPane().add(jLabel7);
        jLabel7.setBounds(-560, -300, 1650, 980);

        Add_marks.setTitle("Add Teacher");
        Add_marks.setLocation(new java.awt.Point(710, 230));
        Add_marks.setMinimumSize(new java.awt.Dimension(448, 460));
        Add_marks.setUndecorated(true);
        Add_marks.setResizable(false);
        Add_marks.getContentPane().setLayout(null);

        jLabel43.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(204, 204, 255));
        jLabel43.setText("Admission No:");
        Add_marks.getContentPane().add(jLabel43);
        jLabel43.setBounds(70, 40, 150, 20);

        jLabel44.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(204, 204, 255));
        jLabel44.setText("English:");
        Add_marks.getContentPane().add(jLabel44);
        jLabel44.setBounds(110, 150, 160, 30);

        jLabel45.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(204, 204, 255));
        jLabel45.setText("Name:");
        Add_marks.getContentPane().add(jLabel45);
        jLabel45.setBounds(130, 80, 130, 20);

        jLabel46.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(204, 204, 255));
        jLabel46.setText("Physics:");
        Add_marks.getContentPane().add(jLabel46);
        jLabel46.setBounds(110, 190, 160, 30);

        jLabel49.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(204, 204, 255));
        jLabel49.setText("Class:");
        Add_marks.getContentPane().add(jLabel49);
        jLabel49.setBounds(130, 120, 110, 20);

        jLabel50.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(204, 204, 255));
        jLabel50.setText("Chemistry:");
        Add_marks.getContentPane().add(jLabel50);
        jLabel50.setBounds(90, 230, 110, 30);

        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        Add_marks.getContentPane().add(a2);
        a2.setBounds(200, 80, 200, 30);
        Add_marks.getContentPane().add(a3);
        a3.setBounds(200, 120, 200, 30);

        a9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a9ActionPerformed(evt);
            }
        });
        Add_marks.getContentPane().add(a9);
        a9.setBounds(200, 360, 200, 30);
        Add_marks.getContentPane().add(a7);
        a7.setBounds(200, 280, 200, 30);

        jLabel51.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(204, 204, 255));
        jLabel51.setText("Maths:");
        Add_marks.getContentPane().add(jLabel51);
        jLabel51.setBounds(120, 270, 90, 30);

        jLabel52.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(204, 204, 255));
        jLabel52.setText("IP:");
        Add_marks.getContentPane().add(jLabel52);
        jLabel52.setBounds(140, 360, 90, 20);

        teachersub2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        teachersub2.setText("Submit");
        teachersub2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        teachersub2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachersub2ActionPerformed(evt);
            }
        });
        Add_marks.getContentPane().add(teachersub2);
        teachersub2.setBounds(110, 400, 120, 30);

        teachersub3.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        teachersub3.setText("Cancel");
        teachersub3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        teachersub3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachersub3ActionPerformed(evt);
            }
        });
        Add_marks.getContentPane().add(teachersub3);
        teachersub3.setBounds(250, 400, 120, 30);

        jLabel53.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(204, 204, 255));
        jLabel53.setText("<html><b>Add Marks</b></html> ");
        Add_marks.getContentPane().add(jLabel53);
        jLabel53.setBounds(180, 0, 160, 30);
        Add_marks.getContentPane().add(jSeparator3);
        jSeparator3.setBounds(-10, 30, 720, 20);

        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        Add_marks.getContentPane().add(a1);
        a1.setBounds(200, 40, 200, 30);
        Add_marks.getContentPane().add(a4);
        a4.setBounds(200, 160, 200, 30);

        a6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a6ActionPerformed(evt);
            }
        });
        Add_marks.getContentPane().add(a6);
        a6.setBounds(200, 240, 200, 30);
        Add_marks.getContentPane().add(a5);
        a5.setBounds(200, 200, 200, 30);

        jLabel55.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(204, 204, 255));
        jLabel55.setText("PEd:");
        Add_marks.getContentPane().add(jLabel55);
        jLabel55.setBounds(130, 310, 90, 30);

        a8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a8ActionPerformed(evt);
            }
        });
        Add_marks.getContentPane().add(a8);
        a8.setBounds(200, 320, 200, 30);

        jLabel54.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(204, 204, 255));
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XII Project/back - Copy.jpg"))); // NOI18N
        Add_marks.getContentPane().add(jLabel54);
        jLabel54.setBounds(0, 0, 1600, 1200);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("School Management System 1.1");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(250, 100));
        setMinimumSize(new java.awt.Dimension(910, 590));
        setUndecorated(true);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Log-in", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("Password:");

        adminRbtn.setBackground(new java.awt.Color(102, 102, 255));
        buttonGroup1.add(adminRbtn);
        adminRbtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        adminRbtn.setSelected(true);
        adminRbtn.setText("Admin");
        adminRbtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                adminRbtnFocusGained(evt);
            }
        });
        adminRbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminRbtnActionPerformed(evt);
            }
        });

        teacherRbtn.setBackground(new java.awt.Color(102, 102, 255));
        buttonGroup1.add(teacherRbtn);
        teacherRbtn.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        teacherRbtn.setText("Teacher");
        teacherRbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherRbtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("Username:");

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton1.setText("Log-in");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(adminRbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(teacherRbtn))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pwdFld, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(usernameCbox, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacherRbtn)
                    .addComponent(adminRbtn))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(usernameCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwdFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(490, 230, 400, 330);

        jLabel19.setBackground(new java.awt.Color(51, 51, 51));
        jLabel19.setFont(new java.awt.Font("Swis721 Cn BT", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Credits");
        jLabel19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel19.setOpaque(true);
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel19);
        jLabel19.setBounds(20, 540, 80, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XII Project/schoolsys-Banner.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-20, 0, 930, 200);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XII Project/Features-of-School-Management-System.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 220, 480, 330);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/XII Project/back - Copy.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 930, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminRbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminRbtnActionPerformed
 usernameCbox.removeAllItems();
        DefaultTableModel model = (DefaultTableModel)adminTbl.getModel();
    try{
        Class.forName("java.sql.Driver");

        Connection con = (Connection) DriverManager.getConnection
                ("jdbc:mysql://localhost/sms","root","root");
        Statement stmt = (Statement) con.createStatement();
        String query = "Select username from admin;";
        ResultSet rs = stmt.executeQuery(query);

        while(rs.next()){
            String a = rs.getString("username");
            usernameCbox.addItem(a);
        }


    }
catch(Exception e){
    JOptionPane.showMessageDialog(null , "error in connectivity");
    }        // TODO add your handling code here:
}//GEN-LAST:event_adminRbtnActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if (teacherRbtn.isSelected()){
    DefaultTableModel model = (DefaultTableModel)studenttbl.getModel();
        try{
        Class.forName("java.sql.Driver");

        Connection con = (Connection) DriverManager.getConnection
                ("jdbc:mysql://localhost/sms","root","root");
        Statement stmt = (Statement) con.createStatement();
        String query = "Select * from teacher;";
        ResultSet rs = stmt.executeQuery(query);

        while(rs.next()){
            String a = rs.getString("id");
            String b = rs.getString("username");
            String c = rs.getString("password");
            model.addRow(new Object[] {a,b,c});
        }

System.out.print(""+1);
   }
catch(Exception e){
    JOptionPane.showMessageDialog(null , "error in connectivity");
    }
    System.out.print(""+2);
    int i = usernameCbox.getSelectedIndex();
    String A = (String) studenttbl.getValueAt(i , 2 );
    String B = new String (pwdFld.getPassword());
   System.out.print(""+3);
    if (B.equals(A)){
        Teacher_frame.setVisible(true);
    }
    else{
        JOptionPane.showMessageDialog(null,"Incorrect Password." );
    }
   System.out.print(""+4);
    }
   else
       if(adminRbtn.isSelected()){
    DefaultTableModel model1 = (DefaultTableModel)adminTbl.getModel();
        try{
        Class.forName("java.sql.Driver");

        Connection con = (Connection) DriverManager.getConnection
                ("jdbc:mysql://localhost/sms","root","root");
        Statement stmt = (Statement) con.createStatement();
        String query = "Select * from admin;";
        ResultSet rs = stmt.executeQuery(query);

        while(rs.next()){
            //String a = rs.getString("id");
            String b = rs.getString("username");
            String c = rs.getString("password");
            model1.addRow(new Object[] {b,c});
        }
         System.out.print(""+5);

        }
catch(Exception e){
    JOptionPane.showMessageDialog(null , "error in connectivity");
    }
    int i =  usernameCbox.getSelectedIndex();
    String A = (String) adminTbl.getValueAt(i, 1); 
    String B = new String (pwdFld.getPassword());
    
   System.out.print(""+6);
    if (B.equals(A)){
        adminFrame.setVisible(true);
        
    }
    else{
        JOptionPane.showMessageDialog(null,"Incorrect Password." );
    }
   System.out.print(""+7);
     }
       else{
        JOptionPane.showMessageDialog(null,"Please enter a valid Username and password");
       }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void teacherRbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherRbtnActionPerformed
 usernameCbox.removeAllItems();
        DefaultTableModel model = (DefaultTableModel)studenttbl.getModel();
    try{
        Class.forName("java.sql.Driver");

        Connection con = (Connection) DriverManager.getConnection
                ("jdbc:mysql://localhost/sms","root","root");
        Statement stmt = (Statement) con.createStatement();
        String query = "Select username from teacher;";
        ResultSet rs = stmt.executeQuery(query);

        while(rs.next()){
            String a = rs.getString("username");
            usernameCbox.addItem(a);
        }


    }
catch(Exception e){
    JOptionPane.showMessageDialog(null , "error in connectivity");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_teacherRbtnActionPerformed

    private void tsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsubActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tsubActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        Add_teacher.setVisible(true);// TODO add your handling code here:
}//GEN-LAST:event_jButton15ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        Add_student.setVisible(true);        // TODO add your handling code here:
}//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        Extra.setVisible(true);        // TODO add your handling code here:
}//GEN-LAST:event_jButton22ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed

        try{

         Class.forName("java.sql.Driver");
DefaultTableModel model = (DefaultTableModel)teacherTbl.getModel();
       while (model.getRowCount()>0){
           model.removeRow(0);
       }
Connection con = (Connection) DriverManager.getConnection
                ("jdbc:mysql://localhost/sms","root","root");
        Statement stmt = (Statement) con.createStatement();
        String query = "Select * from teacher;";
        ResultSet rs = stmt.executeQuery(query);

        while(rs.next()){
            String j = rs.getString("id");
            String a = rs.getString("username");
            String b = rs.getString("password");
            String c = rs.getString("gender");
            String d = rs.getString("qualfication");
            String e = rs.getString("class_teacher");
            String f = rs.getString("subject");
            String g = rs.getString("doj");
            String h = rs.getString("dob");
            
           model.addRow(new Object[] {j,a,b,c,d,e,f,g,h});
        }


    }
catch(Exception e){
    JOptionPane.showMessageDialog(null , "Error in connectivity");
    }

       try{

         Class.forName("java.sql.Driver");
DefaultTableModel model1 = (DefaultTableModel)adminTbl.getModel();
       while (model1.getRowCount()>0){
           model1.removeRow(0);
       }
Connection con1 = (Connection) DriverManager.getConnection
                ("jdbc:mysql://localhost/sms","root","root");
        Statement stmt1 = (Statement) con1.createStatement();
        String query1 = "Select * from admin;";
        ResultSet rs1 = stmt1.executeQuery(query1);

        while(rs1.next()){
            String k = rs1.getString("username");
            String l = rs1.getString("password");

           model1.addRow(new Object[] {k,l});
        }


    }
catch(Exception e){
    JOptionPane.showMessageDialog(null , "error in connectivity");
    }

       try{

         Class.forName("java.sql.Driver");
DefaultTableModel model2 = (DefaultTableModel)studenttbl.getModel();
        while (model2.getRowCount()>0){
           model2.removeRow(0);
       }
Connection con2 = (Connection) DriverManager.getConnection
                ("jdbc:mysql://localhost/sms","root","root");
        Statement stmt2 = (Statement) con2.createStatement();
        String query2 = "Select * from student;";
        ResultSet rs2 = stmt2.executeQuery(query2);

        while(rs2.next()){
            String m = rs2.getString("Name");
            String n = rs2.getString("Admission_No");
            String o = rs2.getString("Gender");
            String p = rs2.getString("Class");
            String q = rs2.getString("Section");
            String r = rs2.getString("DOJ");
            String s = rs2.getString("DOB");

           model2.addRow(new Object[] {m,n,o,p,q,r,s});
        }


    }
catch(Exception e){
    JOptionPane.showMessageDialog(null , "Error in connectivity!");
    } // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void adminRbtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_adminRbtnFocusGained


        usernameCbox.removeAllItems();
        DefaultTableModel model = (DefaultTableModel)adminTbl.getModel();
    try{
        Class.forName("java.sql.Driver");

        Connection con = (Connection) DriverManager.getConnection
                ("jdbc:mysql://localhost/sms","root","root");
        Statement stmt = (Statement) con.createStatement();
        String query = "Select username from admin;";
        ResultSet rs = stmt.executeQuery(query);

        while(rs.next()){
            String a = rs.getString("username");
            usernameCbox.addItem(a);
        }


    }
catch(Exception e){
    JOptionPane.showMessageDialog(null , "Error in connectivity!");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_adminRbtnFocusGained

    private void StSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StSubActionPerformed
String a = StName.getText();
String b = StAdno.getText();
String c = (String) StGen.getSelectedItem();
String d = StClass.getText();
String e = StSec.getText();
String f = StDoj.getText();
String g = StDob.getText();
        try{
 Class.forName("java.sql.Driver");

        Connection con = (Connection) DriverManager.getConnection
                ("jdbc:mysql://localhost/sms","root","root");
        Statement stmt = (Statement) con.createStatement();
        String query = "insert into students values('"+a+"','"+b+"','"+c+"','"+d+"','"+e+"','"+f+"','"+g+"');";
        System.out.print("ok");
        stmt.execute(query);
        System.out.print(query);
        JOptionPane.showMessageDialog(null , "Student Added!");
        }
        catch(Exception h){
    JOptionPane.showMessageDialog(null , "Error in connectivity");
    }       // TODO add your handling code here:
}//GEN-LAST:event_StSubActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void teachersubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachersubActionPerformed
String a = tname.getText();
char[] b = tpass.getPassword();
String c = (String) tgen.getSelectedItem();
String d = tqual.getText();
String e = tclass.getText();
String f = tsub.getText();
String g = tdoj.getText();
String i = b.toString();
String h = tdob.getText();
        try{
 Class.forName("java.sql.Driver");
System.out.print("okfsdfsd");
        Connection con = (Connection) DriverManager.getConnection
                ("jdbc:mysql://localhost/sms","root","root");
        System.out.println("ok");
         String query1 = "select max(id) from teacher;";
        System.out.print("ok");
         Statement stmt = (Statement) con.createStatement();
        System.out.print("ok");
         //ResultSet rs = stmt1.executeQuery(query1);
        System.out.print("ok");
         //int s = rs.getInt(query1)+1;
        
        System.out.print("ok");
         //String t = Integer.toString(s);


        String query = "insert into teacher values(315,'"+a+"','"+b+"','"+c+"','"+d+"','"+e+"','"+f+"','"+g+"','"+h+"');";
        System.out.print(query);
        
        stmt.executeQuery(query);
        
        }
        catch(Exception z){
    JOptionPane.showMessageDialog(null , "error in connectivity");
    }       // TODO add your handling code here:
}//GEN-LAST:event_teachersubActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
remove_teacher.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
String qw= id_remove.getText();
try{
 Class.forName("java.sql.Driver");

        Connection con = (Connection) DriverManager.getConnection
                ("jdbc:mysql://localhost/sms","root","root");
        Statement stmt = (Statement) con.createStatement();
        String query = "delete from teacher where id="+qw+";";
        stmt.execute(query);
        JOptionPane.showMessageDialog(null , "Succesfully Deleted!");
       remove_teacher.dispose();
        }
        catch(Exception o){
    JOptionPane.showMessageDialog(null , "Error! Try Again.");
    }// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
remove_student.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4KeyPressed

    private void tnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnameActionPerformed

    private void teachersub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachersub1ActionPerformed
Add_teacher.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_teachersub1ActionPerformed

    private void StSub1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StSub1ActionPerformed
Add_student.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_StSub1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
adminFrame.dispose();
pwdFld.setText(null);// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
remove_teacher.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
int idRemove2= Integer.parseInt(id_remove2.getText());
try{
 Class.forName("java.sql.Driver");

        Connection con = (Connection) DriverManager.getConnection
                ("jdbc:mysql://localhost/sms","root","root");
        Statement stmt = (Statement) con.createStatement();
        String query = "delete from students where admission_no="+""+idRemove2+";";
        System.out.println(query);
        stmt.execute(query);
        JOptionPane.showMessageDialog(null , "Succesfully Deleted!");
        remove_student.dispose();
        }
        catch(Exception pp){
    JOptionPane.showMessageDialog(null , "Error! Try Again.");
    }// TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
remove_student.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
Teacher_frame.dispose();
pwdFld.setText(null);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
DefaultTableModel model = (DefaultTableModel)student_detail.getModel();
try{

         Class.forName("java.sql.Driver");
       while (model.getRowCount()>0){
           model.removeRow(0);
       }
Connection con = (Connection) DriverManager.getConnection
                ("jdbc:mysql://localhost/sms","root","root");
        Statement stmtx = (Statement) con.createStatement();
        String queryx = "Select * from Students;";
        ResultSet rs = stmtx.executeQuery(queryx);
System.out.println(queryx);
        while(rs.next()){
            String j = rs.getString("Name");
            int a = rs.getInt("Admission_no");
            String b = rs.getString("Gender");
            String c = rs.getString("Class");
            String d = rs.getString("Section");
            String e = rs.getString("DOJ");
            String f = rs.getString("DOB");
            System.out.println("while loop!");
            
           model.addRow(new Object[] {j,a,b,c,d,e,f});
           System.out.println("add row!");
           Student_Details.setVisible(true);
        }
}       catch (Exception yu) {
            JOptionPane.showMessageDialog(null,"Error!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
Marksheet.setVisible(true);
try{

         Class.forName("java.sql.Driver");
DefaultTableModel model = (DefaultTableModel)mark.getModel();
       while (model.getRowCount()>0){
           model.removeRow(0);
       }
Connection con = (Connection) DriverManager.getConnection
                ("jdbc:mysql://localhost/sms","root","root");
        Statement stmt = (Statement) con.createStatement();
        String query = "Select * from marks;";
        ResultSet rs = stmt.executeQuery(query);

        while(rs.next()){
            String j = rs.getString("Admission_no");
            String a = rs.getString("Name");
            String b = rs.getString("Class");
            String c = rs.getString("English");
            String d = rs.getString("Physics");
            String e = rs.getString("Chemistry");
            String f = rs.getString("Maths");
            String g = rs.getString("PEd");
            String h = rs.getString("IP");
            
           model.addRow(new Object[] {j,a,b,c,d,e,f,g,h});
        }
}
        catch(Exception we){
                JOptionPane.showMessageDialog(null,"Error!");
                }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton27ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a2ActionPerformed

    private void a9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a9ActionPerformed

    private void teachersub2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachersub2ActionPerformed
int a =Integer.parseInt(a1.getText());
String b =a2.getText();
String c =a3.getText();
int d =Integer.parseInt(a4.getText());
int e =Integer.parseInt(a5.getText());
int f = Integer.parseInt(a6.getText());
int g = Integer.parseInt(a7.getText());
int h = Integer.parseInt(a8.getText());
int i = Integer.parseInt(a9.getText());
        try{
 Class.forName("java.sql.Driver");
System.out.print("okfsdfsd");
        Connection con = (Connection) DriverManager.getConnection
                ("jdbc:mysql://localhost/sms","root","root");
         Statement stmt = (Statement) con.createStatement();


        String query = "insert into marks values("+a+",'"+b+"',"+c+","+d+","+e+","+f+","+g+","+h+","+i+");";
        System.out.print(query);
        
        stmt.executeQuery(query);
        
        }
        catch(Exception z){
    JOptionPane.showMessageDialog(null , "Error in connectivity");
    }        // TODO add your handling code here:
    }//GEN-LAST:event_teachersub2ActionPerformed

    private void teachersub3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachersub3ActionPerformed
Add_marks.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_teachersub3ActionPerformed

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1ActionPerformed

    private void a6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a6ActionPerformed

    private void a8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a8ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
Add_marks.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
credits.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
credits.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SMS().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame Add_marks;
    private javax.swing.JFrame Add_student;
    private javax.swing.JFrame Add_teacher;
    private javax.swing.JFrame Extra;
    private javax.swing.JFrame Marksheet;
    private javax.swing.JTextField StAdno;
    private javax.swing.JTextField StClass;
    private javax.swing.JFormattedTextField StDob;
    private javax.swing.JFormattedTextField StDoj;
    private javax.swing.JComboBox StGen;
    private javax.swing.JTextField StName;
    private javax.swing.JTextField StSec;
    private javax.swing.JButton StSub;
    private javax.swing.JButton StSub1;
    private javax.swing.JFrame Student_Details;
    private javax.swing.JFrame Teacher_frame;
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField a4;
    private javax.swing.JTextField a5;
    private javax.swing.JTextField a6;
    private javax.swing.JTextField a7;
    private javax.swing.JTextField a8;
    private javax.swing.JTextField a9;
    private javax.swing.JFrame adminFrame;
    private javax.swing.JRadioButton adminRbtn;
    private javax.swing.JTable adminTbl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFrame credits;
    private javax.swing.JTextField id_remove;
    private javax.swing.JTextField id_remove2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JTable mark;
    private javax.swing.JTextField name;
    private javax.swing.JTextField name3;
    private javax.swing.JPasswordField pwdFld;
    private javax.swing.JLabel removeStudentlabel;
    private javax.swing.JFrame remove_student;
    private javax.swing.JFrame remove_teacher;
    private javax.swing.JTable student_detail;
    private javax.swing.JTable studenttbl;
    private javax.swing.JTextField tclass;
    private javax.swing.JFormattedTextField tdob;
    private javax.swing.JFormattedTextField tdoj;
    private javax.swing.JRadioButton teacherRbtn;
    private javax.swing.JTable teacherTbl;
    private javax.swing.JButton teachersub;
    private javax.swing.JButton teachersub1;
    private javax.swing.JButton teachersub2;
    private javax.swing.JButton teachersub3;
    private javax.swing.JComboBox tgen;
    private javax.swing.JTextField tname;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JTextField tqual;
    private javax.swing.JTextField tsub;
    private javax.swing.JComboBox usernameCbox;
    // End of variables declaration//GEN-END:variables
}
